const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});
try{const base=process.env.VORTEX_TEST_URL||'http://127.0.0.1:18765';const c=await browser.newContext({viewport:{width:1440,height:1050}});
if(!(await c.request.post(base+'/api/auth/login',{data:JSON.parse(fs.readFileSync(0,'utf8'))})).ok())throw Error('Login failed');
const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);
await p.waitForFunction(()=>document.querySelectorAll('.book-row').length===8&&document.querySelector('#btcPrice').textContent!=='—',null,{timeout:25000});
await p.waitForFunction(()=>document.querySelector('#plans').childElementCount>0,null,{timeout:30000});
await p.waitForFunction(()=>Number(document.querySelector('#btcTape svg')?.dataset.points)>=55,null,{timeout:25000});
const top=await p.locator('main').evaluate(el=>[...el.children].slice(0,3).map(x=>x.className));
if(!top[0].includes('news-strip')||!top[1].includes('ticker-strip')||!top[2].includes('btc-desk'))throw Error('News/market strips are not first');
if(!await p.locator('#btcTape .btc-area').count()||!await p.locator('#btcAreaFill').count())throw Error('BTC area styling missing');
if(await p.locator('#btcTape svg').evaluate(el=>/NaN|Infinity/.test(el.innerHTML)))throw Error('Invalid chart geometry');
const order=await p.locator('main>section').evaluateAll(els=>els.slice(0,3).map(e=>e.className));
if(!order[0].includes('btc-desk')||!order[1].includes('dash-plans')||!order[2].includes('dash-plans'))throw Error('BTC/order book not above plans');
await p.evaluate(()=>{window.__books=0;window.__btcs=0;VX.live.onBook(()=>window.__books++);VX.live.onTick(b=>{if(b.has('BTCUSDT'))window.__btcs++});});
await p.waitForFunction(()=>window.__books>=5&&window.__btcs>=2,null,{timeout:10000});
const probe=await p.evaluate(()=>({books:window.__books,trades:window.__btcs,depthAge:VX.live.age(VX.live.orderbook),price:VX.live.ticks.BTCUSDT.price}));
const staleRows=await p.evaluate(()=>{const original=VX.live.orderbook;VX.live.orderbook={...original,ts:original.ts-10000};VX.live.bookHandlers.forEach(f=>f(VX.live.orderbook));return document.querySelectorAll('.book-row').length;});
if(staleRows)throw Error('Stale depth retained');
await p.waitForFunction(()=>document.querySelectorAll('.book-row').length===8);
await p.screenshot({path:'qa/btc-desk-desktop.png'});
await p.setViewportSize({width:390,height:844});await p.reload();await p.waitForFunction(()=>document.querySelectorAll('.book-row').length===8&&document.querySelector('#plans').childElementCount>0);await p.screenshot({path:'qa/btc-desk-mobile.png'});
if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('Mobile overflow');
await p.setViewportSize({width:320,height:600});if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('Small mobile overflow');
if(errors.length)throw Error(errors.join('\n'));console.log('PASS: strips first, 1M BTC area chart, streaming depth/price, stale-depth hiding, plans below, mobile layout',JSON.stringify(probe));
}finally{await browser.close()}})().catch(e=>{console.error(e.message);process.exitCode=1;});
