const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});
try{const base=process.env.VORTEX_TEST_URL||'http://127.0.0.1:18765';const c=await browser.newContext({viewport:{width:1440,height:1000}});
if(!(await c.request.post(base+'/api/auth/login',{data:JSON.parse(fs.readFileSync(0,'utf8'))})).ok())throw Error('Login failed');
const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/static/vendor/lightweight-charts.standalone.production.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text())+';(()=>{const create=LightweightCharts.createChart;window.__qaCharts=[];window.LightweightCharts={...LightweightCharts,createChart:(host,options)=>{const chart=create(host,options);window.__qaCharts.push({host:host.id,element:host,chart});return chart;}};})();'});});
await p.goto(base+'/analiz');
await p.locator('#chartScreenshotBtn:not([disabled])').waitFor({timeout:90000});await p.locator('[data-watch-symbol="ETHUSDT"]').waitFor({timeout:30000});
const desktop=await p.locator('#analysisChart').boundingBox(),side=await p.locator('#chartSidebar').boundingBox();
if(desktop.y>240||desktop.height<400||side.x<desktop.x+desktop.width-2)throw Error('Chart-first desktop geometry incorrect');
if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('Desktop overflow');
await p.locator('#indicatorMenuBtn').click();if(!await p.locator('#indicatorMenu').isVisible())throw Error('Indicator menu missing');await p.locator('#indicatorMenuBtn').click();
await p.locator('#chartCursorBtn').click();if(await p.locator('#chartCursorBtn').getAttribute('aria-pressed')!=='false')throw Error('Cursor toggle failed');
await p.locator('#chartZoomInBtn').click();await p.locator('#chartZoomOutBtn').click();await p.locator('#chartFitBtn').click();
await p.locator('#chartFullscreenBtn').click();await p.waitForFunction(()=>Boolean(document.fullscreenElement));await p.locator('#chartFullscreenBtn').click();await p.waitForFunction(()=>!document.fullscreenElement);
await p.locator('[data-chart-interval="1h"]').click();await p.waitForFunction(()=>document.querySelector('#analysisMeta').textContent.startsWith('1h')&&!document.querySelector('#chartScreenshotBtn').disabled,null,{timeout:90000});
await p.locator('#chartSidebarToggle').click();if(await p.locator('#chartSidebar').isVisible())throw Error('Desktop sidebar cannot close');await p.locator('#chartSidebarToggle').click();
await p.waitForTimeout(250);
const ranges=await p.evaluate(()=>{const primary=window.__qaCharts.find(x=>x.host==='analysisChart').chart.timeScale().getVisibleRange();return {primary,expected:Math.floor((Date.now()-(VX.live.serverOffsetMs||0))/3600000)*3600,panes:window.__qaCharts.filter(x=>!x.host&&x.element.isConnected).map(x=>x.chart.timeScale().getVisibleRange()).filter(Boolean)};});
if(ranges.primary.to<ranges.expected-3600)throw Error('Latest candle is outside the visible chart');
if(ranges.panes.some(r=>Math.abs(r.to-ranges.primary.to)>3600||Math.abs(r.from-ranges.primary.from)>3600))throw Error('Indicator time axes are misaligned: '+JSON.stringify(ranges));
await p.screenshot({path:'qa/chart-terminal-desktop.png'});
await p.setViewportSize({width:390,height:844});const mobile=await p.locator('#analysisChart').boundingBox();
if(mobile.y>235||mobile.height<250)throw Error('Chart is below fold on mobile');
if(await p.locator('#chartSidebar').isVisible())throw Error('Mobile sidebar is not tucked away');
await p.locator('#chartSidebarToggle').click();if(!await p.locator('#chartSidebar').isVisible())throw Error('Mobile sidebar will not open');
await p.locator('#chartWatchSearch').fill('ETHUSDT');await p.locator('[data-watch-symbol="ETHUSDT"]').click();
await p.waitForFunction(()=>document.querySelector('#analysisTitle').textContent==='ETHUSDT'&&!document.querySelector('#chartScreenshotBtn').disabled,null,{timeout:90000});
if(await p.locator('#chartSidebar').isVisible())throw Error('Mobile sidebar did not close after selecting symbol');
await p.screenshot({path:'qa/chart-terminal-mobile.png'});
await p.setViewportSize({width:320,height:568});if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('Small mobile overflow');
if(errors.length)throw Error(errors.join('\n'));console.log('PASS: chart at top, large canvas, working timeframe/watchlist/indicators/view/fullscreen controls and mobile drawer',JSON.stringify({desktop,mobile}));
}finally{await browser.close()}})().catch(e=>{console.error(e.message);process.exitCode=1;});
